language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libssl-dev
cache: cargo
rust:
- nightly
matrix:
  allow_failures:
  - rust: beta
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin
  fi
script:
- cargo clean
- cargo build
- cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
deploy:
  provider: cargo
  on:
    tags: true
  token:
    secure: T1Zd6V+0wZP7EjnHSzBtxvHxJX/AE7d9ifP2SnEKz271ptSUum9rH7023Knnyvx6w+g7f7lNPqxEyq25HP9iqqwZ+2fvNjDlXSIHAdZkFJY0x2S+95B0X4TdkF2VbJxlTKk2zZB65wGGrpYF2TqjPPOxMmM3el9bD0kSAOwb1DBTCNOaKEFfE2CDC57roEDPICFqDqpCdiZcxdMRf+Es4Rtyk/6XVJ4fjBSgMjCP5RNGdc2Ii4mFKkYlqaBDytp+fpws0KHsXU9+Wq8H5dptbmxYMWpWItsNPbdRmlB22yNd9hrgceAXjFa/LZBkPPXBJ5p9lBS0ds7urGBn8liLdYJg8aZUTVqATK2Tefh0RrV4ZQK/3osMYRVnvjIzQWaK1P2btNA69bYVZ1l3PjxWZRX8JAOKolhVzCIrTFeawl6r7PMXpXwMbYeNCocqCp1L8R1KwDt0A4Iina1TKM2X5eunmpx9Dj9c6gVLiyeIbsFcD4OOoYp0hrn+wV8P/RiWDyP9hcA893+CENbHsBrt1RPDRNkmwDSJb+yHcONiOsTFrwv56bWgmZht+QU4SOOmdiAb/QW89Eobss0gLlRk8ECdvgRy5gdTQ61/Wb8lqHsGzZzAZ/k5SG3z4PlvLJ2QmIrzP+e05ewkueNjMVA5vizBUqtq9E+Fhfva5y5Ijm8=
