language: rust
rust:
# Waiting for Rust 2018 edition support
#  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose --no-run
matrix:
  allow_failures:
    - rust: nightly